---

- name: logrotate package is installed
  package:
    name: logrotate
    state: present

- name: logrotate is configured
  when: logrotate.cfg_file is not defined
  template:
    src: logrotate.conf
    dest: /etc/logrotate.conf
    backup: yes
