# vim: set ft=yaml ts=2 expandtab:
---

- name: OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: logrotate are installed
  package:
    name: logrotate
    state: present

- debug:
    msg: "{{ logrotate_retention_days|rotate(logrotate_frequency) }}"

- name: logrotate is configured
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    backup: yes

...
